import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {NavBar} from "@/app/components/NavBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "CyberCap",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <NavBar/>
        <div className="min-h-screen">

            {children}
        </div>
        <footer className="bg-[#545E75] text-center lg:text-left">
            <div className="p-4 text-center text-surface dark:text-white">
                © 2025 Copyright:
                <a href="/"> CyberCap</a>
            </div>
        </footer>
        </body>
        </html>
    );
}
